### ISSUE TITLE
App crash while try to open gallery

### ISSUE THREAD

**Issue by jaysathvara1998** [AnilFurkanOkcun/UWMediaPicker-Android#5]
I think glide throws this error while using centerCrop() attribute of glide is used.

I attached the file which contains an 
[error.txt](https://github.com/AnilFurkanOkcun/UWMediaPicker-Android/files/4167095/error.txt)
error log.

**Comment by nvpnair** [comment]
it seems glide removed some functions in 4.9.0
so  use 'com.github.bumptech.glide:glide:4.6.1'

**Comment by AnilFurkanOkcun** [comment]
Sorry for not being able to look earlier. I think this issue is caused by the incompatibility of the glide version in this library with the glide version in your application.
Can you try exclude Glide dependency when adding UWMediaPicker dependency?
In addition, I am updating the library using the 4.9 version of Glide. Let me know if the problem persist

**Comment by AnilFurkanOkcun** [comment]
Please try version 1.2.1 and let me know if the problem persist.
`implementation 'com.github.AnilFurkanOkcun:UWMediaPicker-Android:1.2.1'`
