### ISSUE TITLE
Getting different request code

### ISSUE THREAD

**Issue by ShahnawazDeveloper** [AnilFurkanOkcun/UWMediaPicker-Android#9]
The requestCode i assigned is 1111 but after selecting video onActivityResult request code is different which was any random number.

val VIDEO_PICKER_REQUEST_CODE = 1111

  UwMediaPicker
            .with(this)  // this is fragment
            .setRequestCode(VIDEO_PICKER_REQUEST_CODE)  
            .setGalleryMode(UwMediaPicker.GalleryMode.VideoGallery) 
            .setGridColumnCount(4)          
            .setMaxSelectableMediaCount(1)  
            .open()

**Comment by AnilFurkanOkcun** [comment]
@ShahnawazDeveloper Hi, can you provide example project? Because it's working in sample project and in my personal projects. I would like to investigate it and tried it but I couldn't reproduce this case.

**Comment by ShahnawazDeveloper** [comment]
The thing is I implemented it in the live project so I can not share with you the code.
But if you want to investigate then I can make a sample project for you.
Keep up the good work dude.

**Comment by AnilFurkanOkcun** [comment]
@ShahnawazDeveloper That would be great because I tried with simple activity+fragment project and again the request code I provided was working correctly. If you can give me a sample project, I would like to resolve this. Thank you for using my library and giving feedback. also thank you for your kind words. Have a nice day

**Comment by AnilFurkanOkcun** [comment]
I removed request code by using Android Results Api :)
